ports:
  - port: 8001
    onOpen: open-preview
  - port: 6379
    onOpen: ignore

tasks:
  - name: Start First Terminal
    init: |
      docker-compose pull
      cd consumer_group
      npm install
      cd ../producer
      pip install -r requirements.txt
    command: |
      docker-compose up -d      
      gp sync-done finished
      clear
    openMode: split-left
  - name: Start Second Terminal
    init: |
      cd consumer
      pip install -r requirements.txt
    command: |
      clear
    openMode: split-right
      