version: "3.9"
services:
  redis:
    container_name: redis_streams_hotel_jobs
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure