version: "3.9"
services:
  redis:
    container_name: redis_streams_hotel_jobs
    image: "redis:7.0.3"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure